// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Waiter
{
    public partial class Ml_close
    {
        /// <summary>
        /// model input class for Ml_close.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"k0000")]
            public float K0000 { get; set; }

            [ColumnName(@"k0001")]
            public float K0001 { get; set; }

            [ColumnName(@"k0002")]
            public float K0002 { get; set; }

            [ColumnName(@"k0003")]
            public float K0003 { get; set; }

            [ColumnName(@"k0004")]
            public float K0004 { get; set; }

            [ColumnName(@"k0005")]
            public float K0005 { get; set; }

            [ColumnName(@"k0006")]
            public float K0006 { get; set; }

            [ColumnName(@"k0007")]
            public float K0007 { get; set; }

            [ColumnName(@"k0008")]
            public float K0008 { get; set; }

            [ColumnName(@"k0009")]
            public float K0009 { get; set; }

            [ColumnName(@"k0010")]
            public float K0010 { get; set; }

            [ColumnName(@"k0011")]
            public float K0011 { get; set; }

            [ColumnName(@"k0012")]
            public float K0012 { get; set; }

            [ColumnName(@"k0013")]
            public float K0013 { get; set; }

            [ColumnName(@"k0014")]
            public float K0014 { get; set; }

            [ColumnName(@"k0015")]
            public float K0015 { get; set; }

            [ColumnName(@"k0016")]
            public float K0016 { get; set; }

            [ColumnName(@"k0017")]
            public float K0017 { get; set; }

            [ColumnName(@"k0018")]
            public float K0018 { get; set; }

            [ColumnName(@"k0019")]
            public float K0019 { get; set; }

            [ColumnName(@"k0020")]
            public float K0020 { get; set; }

            [ColumnName(@"k0021")]
            public float K0021 { get; set; }

            [ColumnName(@"k0022")]
            public float K0022 { get; set; }

            [ColumnName(@"k0023")]
            public float K0023 { get; set; }

            [ColumnName(@"k0024")]
            public float K0024 { get; set; }

            [ColumnName(@"k0025")]
            public float K0025 { get; set; }

            [ColumnName(@"k0026")]
            public float K0026 { get; set; }

            [ColumnName(@"k0027")]
            public float K0027 { get; set; }

            [ColumnName(@"k0028")]
            public float K0028 { get; set; }

            [ColumnName(@"k0029")]
            public float K0029 { get; set; }

            [ColumnName(@"k0030")]
            public float K0030 { get; set; }

            [ColumnName(@"k0031")]
            public float K0031 { get; set; }

            [ColumnName(@"k0032")]
            public float K0032 { get; set; }

            [ColumnName(@"k0033")]
            public float K0033 { get; set; }

            [ColumnName(@"k0034")]
            public float K0034 { get; set; }

            [ColumnName(@"k0035")]
            public float K0035 { get; set; }

            [ColumnName(@"k0036")]
            public float K0036 { get; set; }

            [ColumnName(@"k0037")]
            public float K0037 { get; set; }

            [ColumnName(@"k0038")]
            public float K0038 { get; set; }

            [ColumnName(@"k0039")]
            public float K0039 { get; set; }

            [ColumnName(@"k0040")]
            public float K0040 { get; set; }

            [ColumnName(@"k0041")]
            public float K0041 { get; set; }

            [ColumnName(@"k0042")]
            public float K0042 { get; set; }

            [ColumnName(@"k0043")]
            public float K0043 { get; set; }

            [ColumnName(@"k0044")]
            public float K0044 { get; set; }

            [ColumnName(@"k0045")]
            public float K0045 { get; set; }

            [ColumnName(@"k0046")]
            public float K0046 { get; set; }

            [ColumnName(@"k0047")]
            public float K0047 { get; set; }

            [ColumnName(@"k0048")]
            public float K0048 { get; set; }

            [ColumnName(@"k0049")]
            public float K0049 { get; set; }

            [ColumnName(@"k0050")]
            public float K0050 { get; set; }

            [ColumnName(@"k0051")]
            public float K0051 { get; set; }

            [ColumnName(@"k0052")]
            public float K0052 { get; set; }

            [ColumnName(@"k0053")]
            public float K0053 { get; set; }

            [ColumnName(@"k0054")]
            public float K0054 { get; set; }

            [ColumnName(@"k0055")]
            public float K0055 { get; set; }

            [ColumnName(@"k0056")]
            public float K0056 { get; set; }

            [ColumnName(@"k0057")]
            public float K0057 { get; set; }

            [ColumnName(@"k0058")]
            public float K0058 { get; set; }

            [ColumnName(@"k0059")]
            public float K0059 { get; set; }

            [ColumnName(@"will")]
            public float Will { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for Ml_close.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            public float Score { get; set; }
        }
        #endregion

        private static string MLNetModelPath = Path.GetFullPath("ml_close.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
